export const InlineData = [
      invalidModels:[1, 3, 9, 12],
      models:[
            "1": {
                  "model": "123AHY789PNY",
                     "upc": "1234567890123",
                     "value": "55",
                     "nlp": "65",
                     "salesman": "75",
                     "invoice": "55",
                     "map": "60",	
                     "l1": "50",	
                     "l1pay": "5",	
                     "l2": "70",	
                     "l2pay": "7",	
                     "l3": "60",	
                     "l3pay": "6",
                     "msg":"Model is good"
               },
              "2": {
                  "model": "123AHY789PNY",
                     "upc": "1234567890123",
                     "value": "55",
                     "nlp": "65",
                     "salesman": "75",
                     "invoice": "55",
                     "map": "60",	
                     "l1": "50",	
                     "l1pay": "5",	
                     "l2": "70",	
                     "l2pay": "7",	
                     "l3": "60",	
                     "l3pay": "6",
                     "msg":"Model is good"
               },
               "3": {
                  "model": "123AHY789PNY",
                     "upc": "1234567890123",
                     "value": "55",
                     "nlp": "65",
                     "salesman": "75",
                     "invoice": "55",
                     "map": "60",	
                     "l1": "50",	
                     "l1pay": "5",	
                     "l2": "70",	
                     "l2pay": "7",	
                     "l3": "60",	
                     "l3pay": "6",
                     "msg":"Model is good"
               },
               "4": {
                  "model": "123AHY789PNY",
                     "upc": "1234567890123",
                     "value": "55",
                     "nlp": "65",
                     "salesman": "75",
                     "invoice": "55",
                     "map": "60",	
                     "l1": "50",	
                     "l1pay": "5",	
                     "l2": "70",	
                     "l2pay": "7",	
                     "l3": "60",	
                     "l3pay": "6",
                     "msg":"Model is good"
               },
               "5": {
                  "model": "123AHY789PNY",
                     "upc": "1234567890123",
                     "value": "55",
                     "nlp": "65",
                     "salesman": "75",
                     "invoice": "55",
                     "map": "60",	
                     "l1": "50",	
                     "l1pay": "5",	
                     "l2": "70",	
                     "l2pay": "7",	
                     "l3": "60",	
                     "l3pay": "6",
                     "msg":"Model is good"
               },
               "6": {
                  "model": "123AHY789PNY",
                     "upc": "1234567890123",
                     "value": "55",
                     "nlp": "65",
                     "salesman": "75",
                     "invoice": "55",
                     "map": "60",	
                     "l1": "50",	
                     "l1pay": "5",	
                     "l2": "70",	
                     "l2pay": "7",	
                     "l3": "60",	
                     "l3pay": "6",
                     "msg":"Model is good"
               },
               "7": {
                  "model": "123AHY789PNY",
                     "upc": "1234567890123",
                     "value": "55",
                     "nlp": "65",
                     "salesman": "75",
                     "invoice": "55",
                     "map": "60",	
                     "l1": "50",	
                     "l1pay": "5",	
                     "l2": "70",	
                     "l2pay": "7",	
                     "l3": "60",	
                     "l3pay": "6",
                     "msg":"Model is good"
               },
               "8": {
                  "model": "123AHY789PNY",
                     "upc": "1234567890123",
                     "value": "55",
                     "nlp": "65",
                     "salesman": "75",
                     "invoice": "55",
                     "map": "60",	
                     "l1": "50",	
                     "l1pay": "5",	
                     "l2": "70",	
                     "l2pay": "7",	
                     "l3": "60",	
                     "l3pay": "6",
                     "msg":"Model is good"
               },
               "9": {
                  "model": "123AHY789PNY",
                     "upc": "1234567890123",
                     "value": "55",
                     "nlp": "65",
                     "salesman": "75",
                     "invoice": "55",
                     "map": "60",	
                     "l1": "50",	
                     "l1pay": "5",	
                     "l2": "70",	
                     "l2pay": "7",	
                     "l3": "60",	
                     "l3pay": "6",
                     "msg":"Model is good"
               },
               "10": {
                  "model": "123AHY789PNY",
                     "upc": "1234567890123",
                     "value": "55",
                     "nlp": "65",
                     "salesman": "75",
                     "invoice": "55",
                     "map": "60",	
                     "l1": "50",	
                     "l1pay": "5",	
                     "l2": "70",	
                     "l2pay": "7",	
                     "l3": "60",	
                     "l3pay": "6",
                     "msg":"Model is good"
               },
               "11": {
                  "model": "123AHY789PNY",
                     "upc": "1234567890123",
                     "value": "55",
                     "nlp": "65",
                     "salesman": "75",
                     "invoice": "55",
                     "map": "60",	
                     "l1": "50",	
                     "l1pay": "5",	
                     "l2": "70",	
                     "l2pay": "7",	
                     "l3": "60",	
                     "l3pay": "6",
                     "msg":"Model is good"
               },
               "12": {
                  "model": "123AHY789PNY",
                     "upc": "1234567890123",
                     "value": "55",
                     "nlp": "65",
                     "salesman": "75",
                     "invoice": "55",
                     "map": "60",	
                     "l1": "50",	
                     "l1pay": "5",	
                     "l2": "70",	
                     "l2pay": "7",	
                     "l3": "60",	
                     "l3pay": "6",
                     "msg":"Model is good"
               },
               "13": {
                  "model": "123AHY789PNY",
                     "upc": "1234567890123",
                     "value": "55",
                     "nlp": "65",
                     "salesman": "75",
                     "invoice": "55",
                     "map": "60",	
                     "l1": "50",	
                     "l1pay": "5",	
                     "l2": "70",	
                     "l2pay": "7",	
                     "l3": "60",	
                     "l3pay": "6",
                     "msg":"Model is good"
               },
               "14": {
                  "model": "123AHY789PNY",
                     "upc": "1234567890123",
                     "value": "55",
                     "nlp": "65",
                     "salesman": "75",
                     "invoice": "55",
                     "map": "60",	
                     "l1": "50",	
                     "l1pay": "5",	
                     "l2": "70",	
                     "l2pay": "7",	
                     "l3": "60",	
                     "l3pay": "6",
                     "msg":"Model is good"
               },
               "15": {
                  "model": "123AHY789PNY",
                     "upc": "1234567890123",
                     "value": "55",
                     "nlp": "65",
                     "salesman": "75",
                     "invoice": "55",
                     "map": "60",	
                     "l1": "50",	
                     "l1pay": "5",	
                     "l2": "70",	
                     "l2pay": "7",	
                     "l3": "60",	
                     "l3pay": "6",
                     "msg":"Model is good"
               },
      ]
    
    
];